CREATE TABLE enterprises (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)  NOT NULL,
    phone_number VARCHAR(20),
    website      VARCHAR(255),
    email        VARCHAR(100)  NOT NULL,
    description  VARCHAR(500)
);

CREATE TABLE teams (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT        NOT NULL,
    name          VARCHAR(100)  NOT NULL,
    description   VARCHAR(500),
    CONSTRAINT fk_teams_enterprise FOREIGN KEY (enterprise_id) REFERENCES enterprises (id)
);

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    email        VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20)
);

CREATE TABLE team_members (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);
